import formidable from 'formidable';
import fs from 'node:fs/promises';
import path from 'node:path';
import JSZip from 'jszip';
import mammoth from 'mammoth';
import { adminClient, userFromToken } from './_supabase.js';

export const config={api:{bodyParser:false}};
const MAX_FILE_BYTES=Number(process.env.MAX_FILE_BYTES||25*1024*1024);
const CHUNK_CHARS=Number(process.env.AI_CHUNK_CHARS||10000);
function providers(){const out=[];const k=process.env.AI_API_KEY||process.env.ZHIPU_API_KEY||process.env.SILICONFLOW_API_KEY||process.env.GROQ_API_KEY||process.env.OPENROUTER_API_KEY||process.env.OPENAI_API_KEY;if(process.env.AI_API_URL&&k)out.push({name:'custom',url:process.env.AI_API_URL,model:process.env.AI_MODEL||'glm-4-flash',key:k});if(process.env.ZHIPU_API_KEY||process.env.AI_API_KEY)out.push({name:'zhipu',url:'https://open.bigmodel.cn/api/paas/v4/chat/completions',model:process.env.ZHIPU_MODEL||'glm-4-flash',key:process.env.ZHIPU_API_KEY||process.env.AI_API_KEY});if(process.env.SILICONFLOW_API_KEY)out.push({name:'siliconflow',url:'https://api.siliconflow.cn/v1/chat/completions',model:process.env.SILICONFLOW_MODEL||'Qwen/Qwen2.5-7B-Instruct',key:process.env.SILICONFLOW_API_KEY});if(process.env.GROQ_API_KEY)out.push({name:'groq',url:'https://api.groq.com/openai/v1/chat/completions',model:process.env.GROQ_MODEL||'llama-3.1-8b-instant',key:process.env.GROQ_API_KEY});if(process.env.OPENROUTER_API_KEY)out.push({name:'openrouter',url:'https://openrouter.ai/api/v1/chat/completions',model:process.env.OPENROUTER_MODEL||'meta-llama/llama-3.3-70b-instruct:free',key:process.env.OPENROUTER_API_KEY});if(process.env.OPENAI_API_KEY)out.push({name:'openai',url:'https://api.openai.com/v1/chat/completions',model:process.env.AI_MODEL||'gpt-4o-mini',key:process.env.OPENAI_API_KEY});return [...new Map(out.map(x=>[x.url+'|'+x.model,x])).values()]}
async function ai(messages,temp=.2){const ps=providers();if(!ps.length)throw new Error('未配置 AI API Key');let last='';for(const p of ps){try{const r=await fetch(p.url,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${p.key}`},body:JSON.stringify({model:p.model,temperature:temp,messages,stream:false})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`${p.name}: ${d?.error?.message||d?.message||r.status}`);const c=d?.choices?.[0]?.message?.content||d?.data?.choices?.[0]?.message?.content;if(!c)throw new Error(`${p.name}: empty`);return c}catch(e){last=e.message}}throw new Error(last||'AI 请求失败')}
function json(raw){const s=raw.replace(/^```json\s*/i,'').replace(/^```/,'').replace(/```$/,'').trim();const a=s.indexOf('{'),b=s.lastIndexOf('}');if(a<0||b<=a)throw new Error('AI JSON 格式异常');return JSON.parse(s.slice(a,b+1))}
function cleanText(s){return String(s||'').replace(/\u0000/g,' ').replace(/\r/g,'\n').replace(/[ \t]+/g,' ').replace(/\n{3,}/g,'\n\n').trim()}
function htmlToText(s){return cleanText(String(s).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<br\s*\/?>/gi,'\n').replace(/<\/p>|<\/div>|<\/li>|<\/h[1-6]>/gi,'\n').replace(/<[^>]+>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&#39;/g,"'").replace(/&quot;/g,'"'))}
async function parseEpub(fp){const z=await JSZip.loadAsync(await fs.readFile(fp));const c=await z.file('META-INF/container.xml')?.async('string');const rp=c?.match(/full-path=["']([^"']+)["']/i)?.[1];if(!rp)throw new Error('EPUB OPF 定位失败');const opf=await z.file(rp)?.async('string');if(!opf)throw new Error('EPUB OPF 读取失败');const base=path.posix.dirname(rp);const manifest=new Map();for(const m of opf.matchAll(/<item\b([^>]+)>/gi)){const a=m[1],id=a.match(/\bid=["']([^"']+)["']/i)?.[1],href=a.match(/\bhref=["']([^"']+)["']/i)?.[1],media=a.match(/\bmedia-type=["']([^"']+)["']/i)?.[1]||'';if(id&&href)manifest.set(id,{href:decodeURIComponent(href),media})}const spine=[...opf.matchAll(/<itemref\b[^>]*\bidref=["']([^"']+)["'][^>]*>/gi)].map(x=>x[1]);const out=[];for(const id of spine){const item=manifest.get(id);if(!item)continue;const p=path.posix.normalize(path.posix.join(base,item.href));const raw=await z.file(p)?.async('string');if(raw)out.push(htmlToText(raw))}return cleanText(out.join('\n\n'))}
async function extract(fp,name){const ext=path.extname(name).toLowerCase();if(ext==='.txt')return cleanText(await fs.readFile(fp,'utf8'));if(ext==='.docx')return cleanText((await mammoth.extractRawText({path:fp})).value);if(ext==='.epub')return parseEpub(fp);throw new Error('仅支持 TXT / DOCX / EPUB')}
function chunks(text,max=CHUNK_CHARS){const ps=text.split(/\n{2,}/).map(x=>x.trim()).filter(Boolean),out=[];let cur='';for(const p of ps){if(cur&&cur.length+p.length+2>max){out.push(cur);cur=''}if(p.length>max){for(let i=0;i<p.length;i+=max)out.push(p.slice(i,i+max))}else cur+=(cur?'\n\n':'')+p}if(cur)out.push(cur);return out}
async function chunkAI(text,i,total){const prompt=`你是职业小说编辑。分析第${i}/${total}段。只根据文本，不编造。返回 JSON：{"chapter":"若能判断章节编号就写，否则空","scene":"场景","events":[],"characters":[],"character_changes":[],"relationship_changes":[],"plot":[],"foreshadowing":[],"suspense":[],"hooks":[],"techniques":[],"weaknesses":[],"evidence":[]}`;return json(await ai([{role:'system',content:'只输出合法JSON，中文。'}, {role:'user',content:prompt+'\n\n文本：\n'+text}],.15))}
async function hierarchical(filename,text,parts,focus){const summaries=[];for(let i=0;i<parts.length;i++)summaries.push(await chunkAI(parts[i],i+1,parts.length));const groups=[];for(let i=0;i<summaries.length;i+=Math.max(1,Math.ceil(summaries.length/10)))groups.push(summaries.slice(i,i+Math.max(1,Math.ceil(summaries.length/10))));const volume=[];for(let i=0;i<groups.length;i++){volume.push(json(await ai([{role:'system',content:'只输出合法JSON，中文。'}, {role:'user',content:`你是小说卷级编辑。根据这些章节片段事实，形成第${i+1}卷的结构诊断。不要编造。返回 JSON：{"volume":"","summary":"","main_plot":"","subplots":[],"turning_points":[],"character_arcs":[],"relationship_changes":[],"foreshadowing":[],"suspense":[],"hooks":[],"pacing":"","strengths":[],"weaknesses":[],"training":""}\n\n${JSON.stringify(groups[i])}`}],.15)))}const book=json(await ai([{role:'system',content:'只输出合法JSON，中文；评分1-10。'}, {role:'user',content:`你是资深网文主编、文学编辑、写作教练。对《${filename}》做全书级详尽诊断。重点：${focus||'综合分析'}。基于下面章节事实和卷级分析，不虚构。返回 JSON：{"title":"","genre":"","one_sentence_core":"","detailed_synopsis":"","story_structure":{"opening":"","inciting_incident":"","first_turn":"","midpoint":"","climax":"","ending":"","assessment":""},"characters":[],"relationships":[],"plot_threads":[],"conflicts":[],"foreshadowing":[],"suspense":[],"hooks":[],"pacing":{"overall":1,"slow_sections":[],"fast_sections":[],"turning_point_density":"","hook_consistency":""},"writing_techniques":[],"strengths":[],"weaknesses":[],"revision_priority":[],"imitation_exercises":[],"editor_summary":"","confidence":""}\n\n章节事实：${JSON.stringify(summaries).slice(0,120000)}\n卷级分析：${JSON.stringify(volume).slice(0,60000)}`}],.1));return {chapter:summaries,volume,book}}
export default async function handler(req,res){if(req.method!=='POST')return res.status(405).json({error:'仅支持 POST'});let tempPath='';try{const form=formidable({maxFileSize:MAX_FILE_BYTES,multiples:false,keepExtensions:true});const [fields,files]=await form.parse(req);const f=Array.isArray(files.file)?files.file[0]:files.file;if(!f)return res.status(400).json({error:'没有收到文件'});const name=f.originalFilename||f.newFilename; if(!/\.(txt|docx|epub)$/i.test(name))return res.status(400).json({error:'仅支持 TXT / DOCX / EPUB'});tempPath=f.filepath;const text=await extract(tempPath,name);if(text.length<50)return res.status(400).json({error:'解析正文过短'});const parts=chunks(text);const focus=Array.isArray(fields.focus)?fields.focus[0]:fields.focus||'';const report=await hierarchical(name,text,parts,focus);return res.status(200).json({ok:true,filename:name,format:path.extname(name).slice(1).toUpperCase(),characters:text.length,chunks:parts.length,analysis:report});}catch(e){console.error(e);return res.status(500).json({error:e.message||'分析失败'})}finally{if(tempPath)await fs.unlink(tempPath).catch(()=>{})}}
